language: go
go:
- 1.8.x
install:
- go get -t ./...
script:
- make test
before_deploy:
- make cross-build
- make dist
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: v7uXDfn2GguJyZRkHyOKcVXzNly9kOH5cgKBRXQAqxSZpfwjV8n5TaFRqeSsWAgrMP4scBP54gUtXsfLFU7TcHf5tIPEF1lj5C4HX6afXpPr6ImYpVJVUmc3vPIr1xwMupnw/WaIaF9Mq4pcgUXcAw3RMx8tzIysNVI8jnKHH+UR4CEmRY0I7pRPzRjkqo5iEn7GKE9s6OeysnfQSCVDInto8hOACRuWQc+3tC+aALAdHayEiZkP95mcAiZuIpGA16lrErPjxqYqihqALrM7iDC8ZPO5DTIZV12QFuwwIvovq8NP6XNyfgkL6j1n7yorq5H9pMX+DKjG+OiGhLoOSa62aNlf2eKADm6JbbuzGxKokk8lG9rq/9JapbcTzOCvkH+pQpP4hLtCzc5p187bNR1ihDDVkp0TlNxEaSXhAnKsRXAiHYahFun0KTjum+bZ26hBwRMVdILWntrlMfSskxhDymOcUensh+eAW09G9jMFsDAvx48eHtP+w6+Q6VJkSF3y2rhOOlD8M+d/u5Kr52xNtJPlKJLzLyupDpo1HOuEK7xYpn8ARgucPExMXwLPIwjXw/MaKvo7LoFNDcagQRp5wkBNS1LmTm6O1EN5W0cY69znMRAzozu+noMUDzkjAJgZvzSisPtc3FinjMcxYNhSFCqKnA5/Hu+vwYyetHI=
  overwrite: true
  file_glob: true
  file: dist/*.{tar.gz,zip}
  on:
    repo: tzmfreedom/oauth
    tags: true

